### ISSUE TITLE
Document route bindings

### ISSUE THREAD

**Issue by pconnell99** [willmorgan/stub-azure-function-context#21]
Struggling to work out how to pass routing parameters, any chance of a documentation update to show this?

**Comment by dhensby** [comment]
They are the fourth argument to the `http.createTrigger` function (https://github.com/willmorgan/stub-azure-function-context/blob/develop/lib/bindings/http.js#L100)

**Comment by dhensby** [comment]
closing as out of date - this has been improved in v2
