### ISSUE TITLE
Plans for adding more bindings?

### ISSUE THREAD

**Issue by SimonSimCity** [willmorgan/stub-azure-function-context#22]
As I see it, this library currently only supports a limited set of bindings listed at https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings?tabs=csharp#supported-bindings. Are there any plans of including more, or is there some documentation you guys could provide so I myself can look into how feasible it is to create a PR?

I'm specially interested in the `IoT Hub` binding ...

**Comment by dhensby** [comment]
I don't have any experience with the IoT Hub bindings. PR would be welcome, yes.

You'd need to create a file in [lib/bindings](https://github.com/willmorgan/stub-azure-function-context/tree/develop/lib/bindings) which conforms to the same shape as the other binding types.

It would be nicer if this was typescript so the interface was more clearly defined; I've put some effort into it, but the typings for the dependent packages are all over the place.

I appreciate the code required probably isn't that obvious, but they are all essentially either manipulating the context object appropriately in preparation to being passed to the function under test or they are helpers to create a synthetic trigger/binding. Then there's the `handles` function which must return `true` if the passed binding definition (from the `function.json` file) is of the correct type.

**Comment by dhensby** [comment]
Closing as this is an open-ended issue. Creating bindings types is straightforward now.
