### ISSUE TITLE
How to pass context state?

### ISSUE THREAD

**Issue by timjp87** [willmorgan/stub-azure-function-context#31]
Hi,

consider having a function that makes a call to an external database such as Cosmos DB. In the business logic I plan to have an abstract database class for which I can build my own in-memory implementation for testing.

When I run a test the function needs to know if it should use CosmosDB as backend or the in-memory implementation for testing.

My idea was to evaluate "context.state.testing" for this, however I don't seem to be able to set this.

**Comment by dhensby** [comment]
I'd recommend you look into something like [rewire](https://www.npmjs.com/package/rewire), which would allow you to inject a stubbed DB class/instance. You can also use [Sinon](https://www.npmjs.com/package/sinon) for stubbing.

Alternatively you can wrap your own function which can manipulate the context before passing it on.

```js
const { runStubFunctionFromBindings } = require('stub-azure-function-context');
const myFunction = require('../index.js');

describe('a test', () => {
  it('manipulates context', async () => {
    await runStubFunctionFromBindings((context) => {
      Object.assign(context, { state: { testing: true } });
      return myFunction(context);
    });
  });
});
```
